
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` (Docker build aşaması) gerçekten bağlanmaz, sadece
    // şemayı okur — bu yüzden DATABASE_URL yoksa (build ortamı) hata
    // fırlatmak yerine geçersiz bir yedek kullanıyoruz. Gerçek değer
    // runtime'da (migrate/uygulama) env'den gelir.
    url: process.env.DATABASE_URL ?? "postgresql://user:pass@localhost:5432/db",
  },
});
